/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.optional;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Optional;

public class App {
    static ArrayList<Double> mTab = new ArrayList<>();

    public static void main(String[] args) {
        //oblicz(null);

        mTab.addAll(Collections.nCopies(5,10.0));
        for(int i=0;i<5;i++) mTab.add(10.0);


        try {
            System.out.println("Średnia: "+average(mTab));
        } catch (Exception e) {
            e.printStackTrace();
        }

        mTab.removeAll(mTab);

        try {
            System.out.println("Średnia: "+average1(mTab));
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    @NotNull
    static Double average(@Nullable ArrayList<Double> tablica) throws Exception{
        double srednia = 0;

        if(tablica!=null && tablica.size()!=0){

            for(Double value : tablica)
                srednia+=value;

        }else throw new Exception("Nieprawidłowe dane");

        return srednia/tablica.size();
    }

    @NotNull
    static Double average1(@NotNull ArrayList<Double> tablica) throws Exception {
        double srednia = 0;

        if(tablica.size()!=0){

            for(Double value : tablica)
                srednia+=value;

            return srednia/tablica.size();

        }

        throw new Exception("Tablica nie zawiera elementów...");
    }

    @NotNull
    static Double median(@NotNull ArrayList<Double> tablica){

        Collections.sort(tablica);

        return 0.0;
    }
}
