/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.composit;

import com.example.composit.budynek.*;

import java.util.ArrayList;

public class App {
    public static void main(String[] args) {
        ArrayList<Pomieszczenie> pomieszczenia = new ArrayList<>();

        Kuchnia kuchnia = new Kuchnia(5.0, 5.0);
        Szatnia szatnia = new Szatnia(40.0);
        Sala sala = new Sala(5.0, 6.0);
        Toaleta toaleta = new Toaleta(4.0, 4.0);
        SalaWykladowa salaWykladowa = new SalaWykladowa(6.0,8.0,null,null);

        pomieszczenia.add(kuchnia);
        pomieszczenia.add(szatnia);
        pomieszczenia.add(sala);
        pomieszczenia.add(toaleta);

        wyswietl(pomieszczenia);

    }

    public static void wyswietl(ArrayList<Pomieszczenie> pomieszczenia) {
        for (Pomieszczenie pomieszczenie : pomieszczenia) {
            System.out.println(pomieszczenie.getName());
        }
    }
}
