/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.threads;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

public class AppTest {
    @Test
    @Tag("Funkcja")
    public void testAppHasAGreeting() {
        App classUnderTest = new App();
    }
}
