/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.threads;

import javafx.application.Application;
import javafx.event.EventHandler;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.input.KeyCode;
import javafx.scene.input.KeyEvent;
import javafx.scene.paint.Color;
import javafx.scene.shape.Rectangle;
import javafx.stage.Stage;


class Ship{
    Rectangle rect = new Rectangle();
    Scene scene;
    double width;
    double height;

    double bottomMargin = 5;

    EventHandler<KeyEvent> eventHandler = new EventHandler<KeyEvent>() {
        @Override
        public void handle(KeyEvent event) {
            if(event.getCode()== KeyCode.LEFT){
                System.out.println("left");
            }

            if(event.getCode()==KeyCode.RIGHT){
                System.out.println("right");
            }

            event.consume();
        }
    };

    Ship(Group group, Scene scene, double width, double height){

        this.width = width;
        this.height = height;

        this.scene = scene;

        rect.setWidth(this.width);
        rect.setHeight(this.height);

        rect.setFill(Color.BLUE);

        group.getChildren().add(rect);

        redraw();

        scene.setOnKeyPressed(eventHandler);
    }

    public void redraw(){
        rect.setTranslateX(scene.getWidth()/2-width/2);
        rect.setTranslateY(scene.getHeight()-height-bottomMargin);
    }
}

public class App extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception {
        Group group = new Group();
        Scene scene = new Scene(group, 500, 500);

        primaryStage.setScene(scene);
        primaryStage.show();

        Ship ship = new Ship(group,scene,50,20);
    }
}
