/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.threads;

import javafx.application.Application;
import javafx.application.Platform;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.util.ArrayList;

public class App extends Application {
    ArrayList<runningObject> objects = new ArrayList<>();

    Thread animation = new Thread(new Runnable() {
        @Override
        public void run() {
            while (true) {

                Platform.runLater(new Runnable() {
                    @Override
                    public void run() {
                        for (runningObject object : objects)
                            object.compute();
                    }
                });

                try {
                    Thread.sleep(10);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        }
    });

    @Override
    public void start(Stage primaryStage) throws Exception {
        Group group = new Group();
        Scene scene = new Scene(group, 500, 500);

        primaryStage.setScene(scene);
        primaryStage.show();

        for(int i=0;i<1000;i++)
            objects.add(new runningObject(group));

        animation.start();

    }
}
