/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.prototype;

import java.util.ArrayList;

public class App {

    public static void main(String[] args) {

        ArrayList<Object> cars = new ArrayList<>();

        Car bmw = CarFactory.createCar("BMW","2.5","19","450hp","Coupe");
        Car opel = CarFactory.createCar("OpelInsignia","2.0","19","250hp","Coupe");

        cars.add(bmw);
        cars.add(opel);

        CarFactory.setPrototype(bmw);

        for(int i=0;i<10;i++) {
            try {
                cars.add(CarFactory.getCar());
            } catch (CloneNotSupportedException e) {
                e.printStackTrace();
            }
        }

        CarFactory.setPrototype(new Bmw("3.5","19","650hp","Coupe"));

        for(int i=0;i<10;i++) {
            try {
                cars.add(CarFactory.getCar());
            } catch (CloneNotSupportedException e) {
                e.printStackTrace();
            }
        }

        for(Object car0 : cars)
            ((Car)car0).print();
    }
}
